title: Archetype
baseURL: /
params:
  landing_template: home
  palette: blue
  palettes:
    blue:
      sass:
        accent1: '#5f9dd2'
        accent2: '#758ce1'
        accent3: '#e286a9'
        gradient1: '#27a1e3'
        gradient2: '#e7232a'
    green:
      sass:
        accent1: '#54d3cf'
        accent2: '#4f92d1'
        accent3: '#8075e5'
        gradient1: '#16f4cf'
        gradient2: '#6532e5'
menu:
  footer: []
  main:
    - identifier: layouts
      name: Page Layouts
      url: '#'
      weight: 2
    - identifier: normal1
      name: Left Sidebar
      parent: layouts
      url: /left-sidebar
      weight: 1
    - identifier: normal2
      name: Right Sidebar
      parent: layouts
      url: /right-sidebar
      weight: 2
    - identifier: normal3
      name: No Sidebar
      parent: layouts
      url: /no-sidebar
      weight: 3
    - identifier: submenu
      name: Submenu
      parent: layouts
      url: '#'
      weight: 4
    - identifier: normal4
      name: Option One
      parent: submenu
      url: '#'
      weight: 1
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
